deploy:
  stage: deploy
  image: alpine
  before_script:
    - apk add openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -t rsa 144.22.144.218>> ~/.ssh/known_hosts
  script:
    - ssh -o StrictHostKeyChecking=no ubuntu@144.22.144.218 "cd bb-tw-alert/nodejs/; docker-compose down; git pull; npm install; pip3 install openai pymongo; docker-compose up -d"
