@TELEGRAM_TOKEN = 5581380977:AAHRD1sJM0KuOU1asdafWbmivwJPwhTCx7cU

GET http://144.XX.XXX.XXX8:8005/app
###
GET http://144.XX.XXX.XXX8:8005
###
GET https://api.telegram.org/bot{{TELEGRAM_TOKEN}}/sendMessage?chat_id=@bb_alert_tw&text=Posso escrever o que eu quiser aqui?
