version: "3"
services:
  stream:
    environment:
      - TZ=America/Sao_Paulo
    restart: always
    command: node stream.js
    container_name: stream
    networks:
      - main
    build: .
    volumes:
      - .:/usr/src/app
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    env_file:
      - ./.env
  temperature:
    environment:
      - TZ=America/Sao_Paulo
    restart: always
    command: node temperature.js
    container_name: temperature
    networks:
      - main
    build: .
    volumes:
      - .:/usr/src/app
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    env_file:
      - ./.env
  api-server:
    environment:
      - TZ=America/Sao_Paulo
    restart: always
    command: node api-server.js
    container_name: api-server
    networks:
      - main
    build: .
    ports:
      - 8005:8005
    volumes:
      - .:/usr/src/app
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    env_file:
      - ./.env
  telegram-server:
    environment:
      - TZ=America/Sao_Paulo
    restart: always
    command: node telegram-server.js
    container_name: telegram-server
    networks:
      - main
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    env_file:
      - ./.env
