version: "3"
services:
  stream:
    restart: always
    command: node stream.js
    container_name: stream
    build: .
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - .:/usr/src/app
    env_file:
      - ./.env
  temperature:
    restart: always
    command: node temperature.js
    container_name: temperature
    build: .
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - .:/usr/src/app
    env_file:
      - ./.env
  api-server:
    restart: always
    command: node api-server.js
    container_name: api-server
    build: .
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - 8005:8005
    volumes:
      - .:/usr/src/app
    env_file:
      - ./.env
  telegram-server:
    restart: always
    command: node telegram-server.js
    container_name: telegram-server
    build: .
    environment:
      - TZ=America/Sao_Paulo
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app
    env_file:
      - ./.env
