version: "3"
services:
  stream:
    restart: always
    command: node stream.js
    container_name: stream
    build: .
    volumes:
      - .:/usr/src/app
    env_file:
      - ./.env
  temperature:
    restart: always
    command: node temperature.js
    container_name: temperature
    build: .
    volumes:
      - .:/usr/src/app
    env_file:
      - ./.env
  server:
    restart: always
    command: node server.js
    container_name: server
    build: .
    ports:
      - 8005:8005
    volumes:
      - .:/usr/src/app
    env_file:
      - ./.env
